# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)'
    backendServiceArm: 'VSAuthentication'
    backendAzureRmResourceGroupName: 'nyns-rg'
    backendAzureRmStorageAccountName: 'terraformfsstate'
    backendAzureRmContainerName: 'testcontainer'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceNameAzureRM: 'VSAuthentication'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(Build.SourcesDirectory)'
    environmentServiceNameAzureRM: 'VSAuthentication'
